/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.xSpice.impl;

import com.xtext.ravornyo.xspice.xSpice.ACSimulation;
import com.xtext.ravornyo.xspice.xSpice.GeometericSweep;
import com.xtext.ravornyo.xspice.xSpice.XSpicePackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>AC Simulation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.impl.ACSimulationImpl#getSweep <em>Sweep</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ACSimulationImpl extends SimulationImpl implements ACSimulation
{
  /**
   * The cached value of the '{@link #getSweep() <em>Sweep</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSweep()
   * @generated
   * @ordered
   */
  protected GeometericSweep sweep;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ACSimulationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XSpicePackage.Literals.AC_SIMULATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GeometericSweep getSweep()
  {
    return sweep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSweep(GeometericSweep newSweep, NotificationChain msgs)
  {
    GeometericSweep oldSweep = sweep;
    sweep = newSweep;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, XSpicePackage.AC_SIMULATION__SWEEP, oldSweep, newSweep);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSweep(GeometericSweep newSweep)
  {
    if (newSweep != sweep)
    {
      NotificationChain msgs = null;
      if (sweep != null)
        msgs = ((InternalEObject)sweep).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - XSpicePackage.AC_SIMULATION__SWEEP, null, msgs);
      if (newSweep != null)
        msgs = ((InternalEObject)newSweep).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - XSpicePackage.AC_SIMULATION__SWEEP, null, msgs);
      msgs = basicSetSweep(newSweep, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XSpicePackage.AC_SIMULATION__SWEEP, newSweep, newSweep));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case XSpicePackage.AC_SIMULATION__SWEEP:
        return basicSetSweep(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XSpicePackage.AC_SIMULATION__SWEEP:
        return getSweep();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XSpicePackage.AC_SIMULATION__SWEEP:
        setSweep((GeometericSweep)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XSpicePackage.AC_SIMULATION__SWEEP:
        setSweep((GeometericSweep)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XSpicePackage.AC_SIMULATION__SWEEP:
        return sweep != null;
    }
    return super.eIsSet(featureID);
  }

} //ACSimulationImpl
