/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.xSpice.impl;

import com.xtext.ravornyo.xspice.xSpice.CurrentSwitch;
import com.xtext.ravornyo.xspice.xSpice.XSpicePackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Current Switch</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.impl.CurrentSwitchImpl#getControllingSource <em>Controlling Source</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.impl.CurrentSwitchImpl#getModel <em>Model</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.impl.CurrentSwitchImpl#isZeroState <em>Zero State</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CurrentSwitchImpl extends ComponentImpl implements CurrentSwitch
{
  /**
   * The default value of the '{@link #getControllingSource() <em>Controlling Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getControllingSource()
   * @generated
   * @ordered
   */
  protected static final String CONTROLLING_SOURCE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getControllingSource() <em>Controlling Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getControllingSource()
   * @generated
   * @ordered
   */
  protected String controllingSource = CONTROLLING_SOURCE_EDEFAULT;

  /**
   * The default value of the '{@link #getModel() <em>Model</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModel()
   * @generated
   * @ordered
   */
  protected static final String MODEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getModel() <em>Model</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModel()
   * @generated
   * @ordered
   */
  protected String model = MODEL_EDEFAULT;

  /**
   * The default value of the '{@link #isZeroState() <em>Zero State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isZeroState()
   * @generated
   * @ordered
   */
  protected static final boolean ZERO_STATE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isZeroState() <em>Zero State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isZeroState()
   * @generated
   * @ordered
   */
  protected boolean zeroState = ZERO_STATE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CurrentSwitchImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XSpicePackage.Literals.CURRENT_SWITCH;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getControllingSource()
  {
    return controllingSource;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setControllingSource(String newControllingSource)
  {
    String oldControllingSource = controllingSource;
    controllingSource = newControllingSource;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XSpicePackage.CURRENT_SWITCH__CONTROLLING_SOURCE, oldControllingSource, controllingSource));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getModel()
  {
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setModel(String newModel)
  {
    String oldModel = model;
    model = newModel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XSpicePackage.CURRENT_SWITCH__MODEL, oldModel, model));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isZeroState()
  {
    return zeroState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setZeroState(boolean newZeroState)
  {
    boolean oldZeroState = zeroState;
    zeroState = newZeroState;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XSpicePackage.CURRENT_SWITCH__ZERO_STATE, oldZeroState, zeroState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XSpicePackage.CURRENT_SWITCH__CONTROLLING_SOURCE:
        return getControllingSource();
      case XSpicePackage.CURRENT_SWITCH__MODEL:
        return getModel();
      case XSpicePackage.CURRENT_SWITCH__ZERO_STATE:
        return isZeroState();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XSpicePackage.CURRENT_SWITCH__CONTROLLING_SOURCE:
        setControllingSource((String)newValue);
        return;
      case XSpicePackage.CURRENT_SWITCH__MODEL:
        setModel((String)newValue);
        return;
      case XSpicePackage.CURRENT_SWITCH__ZERO_STATE:
        setZeroState((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XSpicePackage.CURRENT_SWITCH__CONTROLLING_SOURCE:
        setControllingSource(CONTROLLING_SOURCE_EDEFAULT);
        return;
      case XSpicePackage.CURRENT_SWITCH__MODEL:
        setModel(MODEL_EDEFAULT);
        return;
      case XSpicePackage.CURRENT_SWITCH__ZERO_STATE:
        setZeroState(ZERO_STATE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XSpicePackage.CURRENT_SWITCH__CONTROLLING_SOURCE:
        return CONTROLLING_SOURCE_EDEFAULT == null ? controllingSource != null : !CONTROLLING_SOURCE_EDEFAULT.equals(controllingSource);
      case XSpicePackage.CURRENT_SWITCH__MODEL:
        return MODEL_EDEFAULT == null ? model != null : !MODEL_EDEFAULT.equals(model);
      case XSpicePackage.CURRENT_SWITCH__ZERO_STATE:
        return zeroState != ZERO_STATE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (controllingSource: ");
    result.append(controllingSource);
    result.append(", model: ");
    result.append(model);
    result.append(", zeroState: ");
    result.append(zeroState);
    result.append(')');
    return result.toString();
  }

} //CurrentSwitchImpl
