/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.xSpice.impl;

import com.xtext.ravornyo.xspice.xSpice.Diode;
import com.xtext.ravornyo.xspice.xSpice.XSpicePackage;

import java.math.BigDecimal;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Diode</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.impl.DiodeImpl#getModel <em>Model</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.impl.DiodeImpl#getArea <em>Area</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.impl.DiodeImpl#isOff <em>Off</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.impl.DiodeImpl#getIc <em>Ic</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.impl.DiodeImpl#getTemp <em>Temp</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DiodeImpl extends ComponentImpl implements Diode
{
  /**
   * The default value of the '{@link #getModel() <em>Model</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModel()
   * @generated
   * @ordered
   */
  protected static final String MODEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getModel() <em>Model</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModel()
   * @generated
   * @ordered
   */
  protected String model = MODEL_EDEFAULT;

  /**
   * The default value of the '{@link #getArea() <em>Area</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArea()
   * @generated
   * @ordered
   */
  protected static final BigDecimal AREA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getArea() <em>Area</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArea()
   * @generated
   * @ordered
   */
  protected BigDecimal area = AREA_EDEFAULT;

  /**
   * The default value of the '{@link #isOff() <em>Off</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOff()
   * @generated
   * @ordered
   */
  protected static final boolean OFF_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isOff() <em>Off</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isOff()
   * @generated
   * @ordered
   */
  protected boolean off = OFF_EDEFAULT;

  /**
   * The default value of the '{@link #getIc() <em>Ic</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIc()
   * @generated
   * @ordered
   */
  protected static final BigDecimal IC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIc() <em>Ic</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIc()
   * @generated
   * @ordered
   */
  protected BigDecimal ic = IC_EDEFAULT;

  /**
   * The default value of the '{@link #getTemp() <em>Temp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTemp()
   * @generated
   * @ordered
   */
  protected static final BigDecimal TEMP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTemp() <em>Temp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTemp()
   * @generated
   * @ordered
   */
  protected BigDecimal temp = TEMP_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DiodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XSpicePackage.Literals.DIODE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getModel()
  {
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setModel(String newModel)
  {
    String oldModel = model;
    model = newModel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XSpicePackage.DIODE__MODEL, oldModel, model));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BigDecimal getArea()
  {
    return area;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setArea(BigDecimal newArea)
  {
    BigDecimal oldArea = area;
    area = newArea;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XSpicePackage.DIODE__AREA, oldArea, area));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isOff()
  {
    return off;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOff(boolean newOff)
  {
    boolean oldOff = off;
    off = newOff;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XSpicePackage.DIODE__OFF, oldOff, off));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BigDecimal getIc()
  {
    return ic;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIc(BigDecimal newIc)
  {
    BigDecimal oldIc = ic;
    ic = newIc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XSpicePackage.DIODE__IC, oldIc, ic));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BigDecimal getTemp()
  {
    return temp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTemp(BigDecimal newTemp)
  {
    BigDecimal oldTemp = temp;
    temp = newTemp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XSpicePackage.DIODE__TEMP, oldTemp, temp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XSpicePackage.DIODE__MODEL:
        return getModel();
      case XSpicePackage.DIODE__AREA:
        return getArea();
      case XSpicePackage.DIODE__OFF:
        return isOff();
      case XSpicePackage.DIODE__IC:
        return getIc();
      case XSpicePackage.DIODE__TEMP:
        return getTemp();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XSpicePackage.DIODE__MODEL:
        setModel((String)newValue);
        return;
      case XSpicePackage.DIODE__AREA:
        setArea((BigDecimal)newValue);
        return;
      case XSpicePackage.DIODE__OFF:
        setOff((Boolean)newValue);
        return;
      case XSpicePackage.DIODE__IC:
        setIc((BigDecimal)newValue);
        return;
      case XSpicePackage.DIODE__TEMP:
        setTemp((BigDecimal)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XSpicePackage.DIODE__MODEL:
        setModel(MODEL_EDEFAULT);
        return;
      case XSpicePackage.DIODE__AREA:
        setArea(AREA_EDEFAULT);
        return;
      case XSpicePackage.DIODE__OFF:
        setOff(OFF_EDEFAULT);
        return;
      case XSpicePackage.DIODE__IC:
        setIc(IC_EDEFAULT);
        return;
      case XSpicePackage.DIODE__TEMP:
        setTemp(TEMP_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XSpicePackage.DIODE__MODEL:
        return MODEL_EDEFAULT == null ? model != null : !MODEL_EDEFAULT.equals(model);
      case XSpicePackage.DIODE__AREA:
        return AREA_EDEFAULT == null ? area != null : !AREA_EDEFAULT.equals(area);
      case XSpicePackage.DIODE__OFF:
        return off != OFF_EDEFAULT;
      case XSpicePackage.DIODE__IC:
        return IC_EDEFAULT == null ? ic != null : !IC_EDEFAULT.equals(ic);
      case XSpicePackage.DIODE__TEMP:
        return TEMP_EDEFAULT == null ? temp != null : !TEMP_EDEFAULT.equals(temp);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (model: ");
    result.append(model);
    result.append(", area: ");
    result.append(area);
    result.append(", off: ");
    result.append(off);
    result.append(", ic: ");
    result.append(ic);
    result.append(", temp: ");
    result.append(temp);
    result.append(')');
    return result.toString();
  }

} //DiodeImpl
