/*
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.ui.tests;

import com.google.inject.Injector;
import com.xtext.ravornyo.xspice.ui.internal.XspiceActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class XSpiceUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XspiceActivator.getInstance().getInjector("com.xtext.ravornyo.xspice.XSpice");
	}

}
