/*
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.ui;

import com.google.inject.Injector;
import com.xtext.ravornyo.xspice.ui.internal.XspiceActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XSpiceExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(XspiceActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		XspiceActivator activator = XspiceActivator.getInstance();
		return activator != null ? activator.getInjector(XspiceActivator.COM_XTEXT_RAVORNYO_XSPICE_XSPICE) : null;
	}

}
