/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.ide;

import com.xtext.ravornyo.xspice.ide.AbstractXSpiceIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XSpiceIdeModule extends AbstractXSpiceIdeModule {
}
