/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.xSpice;

import java.math.BigDecimal;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BJT Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getSaturationCurrent <em>Saturation Current</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getBetaF <em>Beta F</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getEmissionCoefficientForward <em>Emission Coefficient Forward</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getEarlyVoltageForward <em>Early Voltage Forward</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getRollOffForward <em>Roll Off Forward</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getLeakBeCurrent <em>Leak Be Current</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getLeakBeEmissionCoefficient <em>Leak Be Emission Coefficient</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getBetaR <em>Beta R</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getEmissionCoefficientReverse <em>Emission Coefficient Reverse</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getEarlyVoltageReverse <em>Early Voltage Reverse</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getRollOffReverse <em>Roll Off Reverse</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getLeakBcCurrent <em>Leak Bc Current</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getLeakBcEmissionCoefficient <em>Leak Bc Emission Coefficient</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getBaseResist <em>Base Resist</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getBaseCurrentHalfResist <em>Base Current Half Resist</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getMinimumBaseResistance <em>Minimum Base Resistance</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getEmitterResistance <em>Emitter Resistance</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getCollectorResistance <em>Collector Resistance</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getDepletionCapBe <em>Depletion Cap Be</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getPotentialBe <em>Potential Be</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getJunctionExpBe <em>Junction Exp Be</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getTransitTimeForward <em>Transit Time Forward</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getTransitTimeBiasCoefficientForward <em>Transit Time Bias Coefficient Forward</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getTransitTimeForwardVoltageBc <em>Transit Time Forward Voltage Bc</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getTransitTimeHighCurrentForward <em>Transit Time High Current Forward</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getExcessPhase <em>Excess Phase</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getDepletionCapBc <em>Depletion Cap Bc</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getPotentialBc <em>Potential Bc</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getJunctionExpBc <em>Junction Exp Bc</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getBaseFractionBcCap <em>Base Fraction Bc Cap</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getTransitTimeReverse <em>Transit Time Reverse</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getCapCs <em>Cap Cs</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getPotentialSubstrate <em>Potential Substrate</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getExponentialSubstrate <em>Exponential Substrate</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getBetaExponent <em>Beta Exponent</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getEnergyGap <em>Energy Gap</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getTempExpIs <em>Temp Exp Is</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getFlickerNoiseCoefficient <em>Flicker Noise Coefficient</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getFlickerNoiseExponent <em>Flicker Noise Exponent</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getDepletionCapCoefficient <em>Depletion Cap Coefficient</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getNominalTemperature <em>Nominal Temperature</em>}</li>
 * </ul>
 *
 * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel()
 * @model
 * @generated
 */
public interface BJTModel extends Entity
{
  /**
   * Returns the value of the '<em><b>Saturation Current</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Saturation Current</em>' attribute.
   * @see #setSaturationCurrent(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_SaturationCurrent()
   * @model
   * @generated
   */
  BigDecimal getSaturationCurrent();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getSaturationCurrent <em>Saturation Current</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Saturation Current</em>' attribute.
   * @see #getSaturationCurrent()
   * @generated
   */
  void setSaturationCurrent(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Beta F</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Beta F</em>' attribute.
   * @see #setBetaF(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_BetaF()
   * @model
   * @generated
   */
  BigDecimal getBetaF();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getBetaF <em>Beta F</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Beta F</em>' attribute.
   * @see #getBetaF()
   * @generated
   */
  void setBetaF(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Emission Coefficient Forward</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Emission Coefficient Forward</em>' attribute.
   * @see #setEmissionCoefficientForward(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_EmissionCoefficientForward()
   * @model
   * @generated
   */
  BigDecimal getEmissionCoefficientForward();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getEmissionCoefficientForward <em>Emission Coefficient Forward</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Emission Coefficient Forward</em>' attribute.
   * @see #getEmissionCoefficientForward()
   * @generated
   */
  void setEmissionCoefficientForward(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Early Voltage Forward</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Early Voltage Forward</em>' attribute.
   * @see #setEarlyVoltageForward(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_EarlyVoltageForward()
   * @model
   * @generated
   */
  BigDecimal getEarlyVoltageForward();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getEarlyVoltageForward <em>Early Voltage Forward</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Early Voltage Forward</em>' attribute.
   * @see #getEarlyVoltageForward()
   * @generated
   */
  void setEarlyVoltageForward(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Roll Off Forward</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Roll Off Forward</em>' attribute.
   * @see #setRollOffForward(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_RollOffForward()
   * @model
   * @generated
   */
  BigDecimal getRollOffForward();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getRollOffForward <em>Roll Off Forward</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Roll Off Forward</em>' attribute.
   * @see #getRollOffForward()
   * @generated
   */
  void setRollOffForward(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Leak Be Current</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Leak Be Current</em>' attribute.
   * @see #setLeakBeCurrent(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_LeakBeCurrent()
   * @model
   * @generated
   */
  BigDecimal getLeakBeCurrent();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getLeakBeCurrent <em>Leak Be Current</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Leak Be Current</em>' attribute.
   * @see #getLeakBeCurrent()
   * @generated
   */
  void setLeakBeCurrent(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Leak Be Emission Coefficient</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Leak Be Emission Coefficient</em>' attribute.
   * @see #setLeakBeEmissionCoefficient(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_LeakBeEmissionCoefficient()
   * @model
   * @generated
   */
  BigDecimal getLeakBeEmissionCoefficient();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getLeakBeEmissionCoefficient <em>Leak Be Emission Coefficient</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Leak Be Emission Coefficient</em>' attribute.
   * @see #getLeakBeEmissionCoefficient()
   * @generated
   */
  void setLeakBeEmissionCoefficient(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Beta R</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Beta R</em>' attribute.
   * @see #setBetaR(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_BetaR()
   * @model
   * @generated
   */
  BigDecimal getBetaR();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getBetaR <em>Beta R</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Beta R</em>' attribute.
   * @see #getBetaR()
   * @generated
   */
  void setBetaR(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Emission Coefficient Reverse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Emission Coefficient Reverse</em>' attribute.
   * @see #setEmissionCoefficientReverse(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_EmissionCoefficientReverse()
   * @model
   * @generated
   */
  BigDecimal getEmissionCoefficientReverse();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getEmissionCoefficientReverse <em>Emission Coefficient Reverse</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Emission Coefficient Reverse</em>' attribute.
   * @see #getEmissionCoefficientReverse()
   * @generated
   */
  void setEmissionCoefficientReverse(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Early Voltage Reverse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Early Voltage Reverse</em>' attribute.
   * @see #setEarlyVoltageReverse(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_EarlyVoltageReverse()
   * @model
   * @generated
   */
  BigDecimal getEarlyVoltageReverse();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getEarlyVoltageReverse <em>Early Voltage Reverse</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Early Voltage Reverse</em>' attribute.
   * @see #getEarlyVoltageReverse()
   * @generated
   */
  void setEarlyVoltageReverse(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Roll Off Reverse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Roll Off Reverse</em>' attribute.
   * @see #setRollOffReverse(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_RollOffReverse()
   * @model
   * @generated
   */
  BigDecimal getRollOffReverse();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getRollOffReverse <em>Roll Off Reverse</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Roll Off Reverse</em>' attribute.
   * @see #getRollOffReverse()
   * @generated
   */
  void setRollOffReverse(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Leak Bc Current</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Leak Bc Current</em>' attribute.
   * @see #setLeakBcCurrent(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_LeakBcCurrent()
   * @model
   * @generated
   */
  BigDecimal getLeakBcCurrent();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getLeakBcCurrent <em>Leak Bc Current</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Leak Bc Current</em>' attribute.
   * @see #getLeakBcCurrent()
   * @generated
   */
  void setLeakBcCurrent(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Leak Bc Emission Coefficient</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Leak Bc Emission Coefficient</em>' attribute.
   * @see #setLeakBcEmissionCoefficient(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_LeakBcEmissionCoefficient()
   * @model
   * @generated
   */
  BigDecimal getLeakBcEmissionCoefficient();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getLeakBcEmissionCoefficient <em>Leak Bc Emission Coefficient</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Leak Bc Emission Coefficient</em>' attribute.
   * @see #getLeakBcEmissionCoefficient()
   * @generated
   */
  void setLeakBcEmissionCoefficient(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Base Resist</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base Resist</em>' attribute.
   * @see #setBaseResist(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_BaseResist()
   * @model
   * @generated
   */
  BigDecimal getBaseResist();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getBaseResist <em>Base Resist</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base Resist</em>' attribute.
   * @see #getBaseResist()
   * @generated
   */
  void setBaseResist(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Base Current Half Resist</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base Current Half Resist</em>' attribute.
   * @see #setBaseCurrentHalfResist(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_BaseCurrentHalfResist()
   * @model
   * @generated
   */
  BigDecimal getBaseCurrentHalfResist();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getBaseCurrentHalfResist <em>Base Current Half Resist</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base Current Half Resist</em>' attribute.
   * @see #getBaseCurrentHalfResist()
   * @generated
   */
  void setBaseCurrentHalfResist(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Minimum Base Resistance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minimum Base Resistance</em>' attribute.
   * @see #setMinimumBaseResistance(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_MinimumBaseResistance()
   * @model
   * @generated
   */
  BigDecimal getMinimumBaseResistance();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getMinimumBaseResistance <em>Minimum Base Resistance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Minimum Base Resistance</em>' attribute.
   * @see #getMinimumBaseResistance()
   * @generated
   */
  void setMinimumBaseResistance(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Emitter Resistance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Emitter Resistance</em>' attribute.
   * @see #setEmitterResistance(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_EmitterResistance()
   * @model
   * @generated
   */
  BigDecimal getEmitterResistance();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getEmitterResistance <em>Emitter Resistance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Emitter Resistance</em>' attribute.
   * @see #getEmitterResistance()
   * @generated
   */
  void setEmitterResistance(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Collector Resistance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Collector Resistance</em>' attribute.
   * @see #setCollectorResistance(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_CollectorResistance()
   * @model
   * @generated
   */
  BigDecimal getCollectorResistance();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getCollectorResistance <em>Collector Resistance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Collector Resistance</em>' attribute.
   * @see #getCollectorResistance()
   * @generated
   */
  void setCollectorResistance(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Depletion Cap Be</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Depletion Cap Be</em>' attribute.
   * @see #setDepletionCapBe(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_DepletionCapBe()
   * @model
   * @generated
   */
  BigDecimal getDepletionCapBe();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getDepletionCapBe <em>Depletion Cap Be</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Depletion Cap Be</em>' attribute.
   * @see #getDepletionCapBe()
   * @generated
   */
  void setDepletionCapBe(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Potential Be</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Potential Be</em>' attribute.
   * @see #setPotentialBe(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_PotentialBe()
   * @model
   * @generated
   */
  BigDecimal getPotentialBe();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getPotentialBe <em>Potential Be</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Potential Be</em>' attribute.
   * @see #getPotentialBe()
   * @generated
   */
  void setPotentialBe(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Junction Exp Be</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Junction Exp Be</em>' attribute.
   * @see #setJunctionExpBe(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_JunctionExpBe()
   * @model
   * @generated
   */
  BigDecimal getJunctionExpBe();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getJunctionExpBe <em>Junction Exp Be</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Junction Exp Be</em>' attribute.
   * @see #getJunctionExpBe()
   * @generated
   */
  void setJunctionExpBe(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Transit Time Forward</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transit Time Forward</em>' attribute.
   * @see #setTransitTimeForward(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_TransitTimeForward()
   * @model
   * @generated
   */
  BigDecimal getTransitTimeForward();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getTransitTimeForward <em>Transit Time Forward</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transit Time Forward</em>' attribute.
   * @see #getTransitTimeForward()
   * @generated
   */
  void setTransitTimeForward(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Transit Time Bias Coefficient Forward</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transit Time Bias Coefficient Forward</em>' attribute.
   * @see #setTransitTimeBiasCoefficientForward(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_TransitTimeBiasCoefficientForward()
   * @model
   * @generated
   */
  BigDecimal getTransitTimeBiasCoefficientForward();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getTransitTimeBiasCoefficientForward <em>Transit Time Bias Coefficient Forward</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transit Time Bias Coefficient Forward</em>' attribute.
   * @see #getTransitTimeBiasCoefficientForward()
   * @generated
   */
  void setTransitTimeBiasCoefficientForward(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Transit Time Forward Voltage Bc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transit Time Forward Voltage Bc</em>' attribute.
   * @see #setTransitTimeForwardVoltageBc(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_TransitTimeForwardVoltageBc()
   * @model
   * @generated
   */
  BigDecimal getTransitTimeForwardVoltageBc();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getTransitTimeForwardVoltageBc <em>Transit Time Forward Voltage Bc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transit Time Forward Voltage Bc</em>' attribute.
   * @see #getTransitTimeForwardVoltageBc()
   * @generated
   */
  void setTransitTimeForwardVoltageBc(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Transit Time High Current Forward</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transit Time High Current Forward</em>' attribute.
   * @see #setTransitTimeHighCurrentForward(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_TransitTimeHighCurrentForward()
   * @model
   * @generated
   */
  BigDecimal getTransitTimeHighCurrentForward();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getTransitTimeHighCurrentForward <em>Transit Time High Current Forward</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transit Time High Current Forward</em>' attribute.
   * @see #getTransitTimeHighCurrentForward()
   * @generated
   */
  void setTransitTimeHighCurrentForward(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Excess Phase</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Excess Phase</em>' attribute.
   * @see #setExcessPhase(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_ExcessPhase()
   * @model
   * @generated
   */
  BigDecimal getExcessPhase();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getExcessPhase <em>Excess Phase</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Excess Phase</em>' attribute.
   * @see #getExcessPhase()
   * @generated
   */
  void setExcessPhase(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Depletion Cap Bc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Depletion Cap Bc</em>' attribute.
   * @see #setDepletionCapBc(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_DepletionCapBc()
   * @model
   * @generated
   */
  BigDecimal getDepletionCapBc();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getDepletionCapBc <em>Depletion Cap Bc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Depletion Cap Bc</em>' attribute.
   * @see #getDepletionCapBc()
   * @generated
   */
  void setDepletionCapBc(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Potential Bc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Potential Bc</em>' attribute.
   * @see #setPotentialBc(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_PotentialBc()
   * @model
   * @generated
   */
  BigDecimal getPotentialBc();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getPotentialBc <em>Potential Bc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Potential Bc</em>' attribute.
   * @see #getPotentialBc()
   * @generated
   */
  void setPotentialBc(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Junction Exp Bc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Junction Exp Bc</em>' attribute.
   * @see #setJunctionExpBc(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_JunctionExpBc()
   * @model
   * @generated
   */
  BigDecimal getJunctionExpBc();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getJunctionExpBc <em>Junction Exp Bc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Junction Exp Bc</em>' attribute.
   * @see #getJunctionExpBc()
   * @generated
   */
  void setJunctionExpBc(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Base Fraction Bc Cap</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base Fraction Bc Cap</em>' attribute.
   * @see #setBaseFractionBcCap(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_BaseFractionBcCap()
   * @model
   * @generated
   */
  BigDecimal getBaseFractionBcCap();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getBaseFractionBcCap <em>Base Fraction Bc Cap</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base Fraction Bc Cap</em>' attribute.
   * @see #getBaseFractionBcCap()
   * @generated
   */
  void setBaseFractionBcCap(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Transit Time Reverse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transit Time Reverse</em>' attribute.
   * @see #setTransitTimeReverse(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_TransitTimeReverse()
   * @model
   * @generated
   */
  BigDecimal getTransitTimeReverse();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getTransitTimeReverse <em>Transit Time Reverse</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transit Time Reverse</em>' attribute.
   * @see #getTransitTimeReverse()
   * @generated
   */
  void setTransitTimeReverse(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Cap Cs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cap Cs</em>' attribute.
   * @see #setCapCs(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_CapCs()
   * @model
   * @generated
   */
  BigDecimal getCapCs();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getCapCs <em>Cap Cs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cap Cs</em>' attribute.
   * @see #getCapCs()
   * @generated
   */
  void setCapCs(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Potential Substrate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Potential Substrate</em>' attribute.
   * @see #setPotentialSubstrate(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_PotentialSubstrate()
   * @model
   * @generated
   */
  BigDecimal getPotentialSubstrate();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getPotentialSubstrate <em>Potential Substrate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Potential Substrate</em>' attribute.
   * @see #getPotentialSubstrate()
   * @generated
   */
  void setPotentialSubstrate(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Exponential Substrate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exponential Substrate</em>' attribute.
   * @see #setExponentialSubstrate(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_ExponentialSubstrate()
   * @model
   * @generated
   */
  BigDecimal getExponentialSubstrate();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getExponentialSubstrate <em>Exponential Substrate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exponential Substrate</em>' attribute.
   * @see #getExponentialSubstrate()
   * @generated
   */
  void setExponentialSubstrate(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Beta Exponent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Beta Exponent</em>' attribute.
   * @see #setBetaExponent(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_BetaExponent()
   * @model
   * @generated
   */
  BigDecimal getBetaExponent();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getBetaExponent <em>Beta Exponent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Beta Exponent</em>' attribute.
   * @see #getBetaExponent()
   * @generated
   */
  void setBetaExponent(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Energy Gap</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Energy Gap</em>' attribute.
   * @see #setEnergyGap(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_EnergyGap()
   * @model
   * @generated
   */
  BigDecimal getEnergyGap();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getEnergyGap <em>Energy Gap</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Energy Gap</em>' attribute.
   * @see #getEnergyGap()
   * @generated
   */
  void setEnergyGap(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Temp Exp Is</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temp Exp Is</em>' attribute.
   * @see #setTempExpIs(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_TempExpIs()
   * @model
   * @generated
   */
  BigDecimal getTempExpIs();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getTempExpIs <em>Temp Exp Is</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Temp Exp Is</em>' attribute.
   * @see #getTempExpIs()
   * @generated
   */
  void setTempExpIs(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Flicker Noise Coefficient</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flicker Noise Coefficient</em>' attribute.
   * @see #setFlickerNoiseCoefficient(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_FlickerNoiseCoefficient()
   * @model
   * @generated
   */
  BigDecimal getFlickerNoiseCoefficient();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getFlickerNoiseCoefficient <em>Flicker Noise Coefficient</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Flicker Noise Coefficient</em>' attribute.
   * @see #getFlickerNoiseCoefficient()
   * @generated
   */
  void setFlickerNoiseCoefficient(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Flicker Noise Exponent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flicker Noise Exponent</em>' attribute.
   * @see #setFlickerNoiseExponent(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_FlickerNoiseExponent()
   * @model
   * @generated
   */
  BigDecimal getFlickerNoiseExponent();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getFlickerNoiseExponent <em>Flicker Noise Exponent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Flicker Noise Exponent</em>' attribute.
   * @see #getFlickerNoiseExponent()
   * @generated
   */
  void setFlickerNoiseExponent(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Depletion Cap Coefficient</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Depletion Cap Coefficient</em>' attribute.
   * @see #setDepletionCapCoefficient(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_DepletionCapCoefficient()
   * @model
   * @generated
   */
  BigDecimal getDepletionCapCoefficient();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getDepletionCapCoefficient <em>Depletion Cap Coefficient</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Depletion Cap Coefficient</em>' attribute.
   * @see #getDepletionCapCoefficient()
   * @generated
   */
  void setDepletionCapCoefficient(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Nominal Temperature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nominal Temperature</em>' attribute.
   * @see #setNominalTemperature(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getBJTModel_NominalTemperature()
   * @model
   * @generated
   */
  BigDecimal getNominalTemperature();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.BJTModel#getNominalTemperature <em>Nominal Temperature</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nominal Temperature</em>' attribute.
   * @see #getNominalTemperature()
   * @generated
   */
  void setNominalTemperature(BigDecimal value);

} // BJTModel
