/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.xSpice;

import java.math.BigDecimal;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CCCS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.CCCS#getController <em>Controller</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.CCCS#getGain <em>Gain</em>}</li>
 * </ul>
 *
 * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCCCS()
 * @model
 * @generated
 */
public interface CCCS extends Component
{
  /**
   * Returns the value of the '<em><b>Controller</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Controller</em>' attribute.
   * @see #setController(String)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCCCS_Controller()
   * @model
   * @generated
   */
  String getController();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.CCCS#getController <em>Controller</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Controller</em>' attribute.
   * @see #getController()
   * @generated
   */
  void setController(String value);

  /**
   * Returns the value of the '<em><b>Gain</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gain</em>' attribute.
   * @see #setGain(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCCCS_Gain()
   * @model
   * @generated
   */
  BigDecimal getGain();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.CCCS#getGain <em>Gain</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gain</em>' attribute.
   * @see #getGain()
   * @generated
   */
  void setGain(BigDecimal value);

} // CCCS
