/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.xSpice;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Compilation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.Compilation#getDefinitions <em>Definitions</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.Compilation#getEntities <em>Entities</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.Compilation#getSimulations <em>Simulations</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.Compilation#getOutputs <em>Outputs</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.Compilation#getOptions <em>Options</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.Compilation#getIc <em>Ic</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.Compilation#getNodeset <em>Nodeset</em>}</li>
 * </ul>
 *
 * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCompilation()
 * @model
 * @generated
 */
public interface Compilation extends EObject
{
  /**
   * Returns the value of the '<em><b>Definitions</b></em>' containment reference list.
   * The list contents are of type {@link com.xtext.ravornyo.xspice.xSpice.SubCircuitDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Definitions</em>' containment reference list.
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCompilation_Definitions()
   * @model containment="true"
   * @generated
   */
  EList<SubCircuitDefinition> getDefinitions();

  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link com.xtext.ravornyo.xspice.xSpice.Entity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCompilation_Entities()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntities();

  /**
   * Returns the value of the '<em><b>Simulations</b></em>' containment reference list.
   * The list contents are of type {@link com.xtext.ravornyo.xspice.xSpice.Simulation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simulations</em>' containment reference list.
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCompilation_Simulations()
   * @model containment="true"
   * @generated
   */
  EList<Simulation> getSimulations();

  /**
   * Returns the value of the '<em><b>Outputs</b></em>' containment reference list.
   * The list contents are of type {@link com.xtext.ravornyo.xspice.xSpice.Output}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Outputs</em>' containment reference list.
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCompilation_Outputs()
   * @model containment="true"
   * @generated
   */
  EList<Output> getOutputs();

  /**
   * Returns the value of the '<em><b>Options</b></em>' containment reference list.
   * The list contents are of type {@link com.xtext.ravornyo.xspice.xSpice.Options}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Options</em>' containment reference list.
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCompilation_Options()
   * @model containment="true"
   * @generated
   */
  EList<Options> getOptions();

  /**
   * Returns the value of the '<em><b>Ic</b></em>' containment reference list.
   * The list contents are of type {@link com.xtext.ravornyo.xspice.xSpice.InitialCondition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ic</em>' containment reference list.
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCompilation_Ic()
   * @model containment="true"
   * @generated
   */
  EList<InitialCondition> getIc();

  /**
   * Returns the value of the '<em><b>Nodeset</b></em>' containment reference list.
   * The list contents are of type {@link com.xtext.ravornyo.xspice.xSpice.NodeSet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodeset</em>' containment reference list.
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCompilation_Nodeset()
   * @model containment="true"
   * @generated
   */
  EList<NodeSet> getNodeset();

} // Compilation
