/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.xSpice;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.Component#getNodes <em>Nodes</em>}</li>
 * </ul>
 *
 * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getComponent()
 * @model
 * @generated
 */
public interface Component extends Entity
{
  /**
   * Returns the value of the '<em><b>Nodes</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodes</em>' attribute list.
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getComponent_Nodes()
   * @model unique="false"
   * @generated
   */
  EList<String> getNodes();

} // Component
