/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.xSpice;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Current Switch</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.CurrentSwitch#getControllingSource <em>Controlling Source</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.CurrentSwitch#getModel <em>Model</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.CurrentSwitch#isZeroState <em>Zero State</em>}</li>
 * </ul>
 *
 * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCurrentSwitch()
 * @model
 * @generated
 */
public interface CurrentSwitch extends Component
{
  /**
   * Returns the value of the '<em><b>Controlling Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Controlling Source</em>' attribute.
   * @see #setControllingSource(String)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCurrentSwitch_ControllingSource()
   * @model
   * @generated
   */
  String getControllingSource();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.CurrentSwitch#getControllingSource <em>Controlling Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Controlling Source</em>' attribute.
   * @see #getControllingSource()
   * @generated
   */
  void setControllingSource(String value);

  /**
   * Returns the value of the '<em><b>Model</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' attribute.
   * @see #setModel(String)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCurrentSwitch_Model()
   * @model
   * @generated
   */
  String getModel();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.CurrentSwitch#getModel <em>Model</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' attribute.
   * @see #getModel()
   * @generated
   */
  void setModel(String value);

  /**
   * Returns the value of the '<em><b>Zero State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zero State</em>' attribute.
   * @see #setZeroState(boolean)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getCurrentSwitch_ZeroState()
   * @model
   * @generated
   */
  boolean isZeroState();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.CurrentSwitch#isZeroState <em>Zero State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Zero State</em>' attribute.
   * @see #isZeroState()
   * @generated
   */
  void setZeroState(boolean value);

} // CurrentSwitch
