/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.xSpice;

import java.math.BigDecimal;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JFET Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getThreshold <em>Threshold</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getBeta <em>Beta</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getLambda <em>Lambda</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getDrainResistance <em>Drain Resistance</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getSourceResistance <em>Source Resistance</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getCapGs <em>Cap Gs</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getCapGd <em>Cap Gd</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getGatePotential <em>Gate Potential</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getGateSaturationCurrent <em>Gate Saturation Current</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getB <em>B</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getFlickerNoiseCoefficient <em>Flicker Noise Coefficient</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getFlickerNoiseExponent <em>Flicker Noise Exponent</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getDepletionCapCoefficient <em>Depletion Cap Coefficient</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getNominalTemperature <em>Nominal Temperature</em>}</li>
 * </ul>
 *
 * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel()
 * @model
 * @generated
 */
public interface JFETModel extends Entity
{
  /**
   * Returns the value of the '<em><b>Threshold</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Threshold</em>' attribute.
   * @see #setThreshold(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel_Threshold()
   * @model
   * @generated
   */
  BigDecimal getThreshold();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getThreshold <em>Threshold</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Threshold</em>' attribute.
   * @see #getThreshold()
   * @generated
   */
  void setThreshold(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Beta</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Beta</em>' attribute.
   * @see #setBeta(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel_Beta()
   * @model
   * @generated
   */
  BigDecimal getBeta();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getBeta <em>Beta</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Beta</em>' attribute.
   * @see #getBeta()
   * @generated
   */
  void setBeta(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Lambda</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lambda</em>' attribute.
   * @see #setLambda(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel_Lambda()
   * @model
   * @generated
   */
  BigDecimal getLambda();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getLambda <em>Lambda</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lambda</em>' attribute.
   * @see #getLambda()
   * @generated
   */
  void setLambda(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Drain Resistance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Drain Resistance</em>' attribute.
   * @see #setDrainResistance(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel_DrainResistance()
   * @model
   * @generated
   */
  BigDecimal getDrainResistance();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getDrainResistance <em>Drain Resistance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Drain Resistance</em>' attribute.
   * @see #getDrainResistance()
   * @generated
   */
  void setDrainResistance(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Source Resistance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Resistance</em>' attribute.
   * @see #setSourceResistance(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel_SourceResistance()
   * @model
   * @generated
   */
  BigDecimal getSourceResistance();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getSourceResistance <em>Source Resistance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Resistance</em>' attribute.
   * @see #getSourceResistance()
   * @generated
   */
  void setSourceResistance(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Cap Gs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cap Gs</em>' attribute.
   * @see #setCapGs(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel_CapGs()
   * @model
   * @generated
   */
  BigDecimal getCapGs();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getCapGs <em>Cap Gs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cap Gs</em>' attribute.
   * @see #getCapGs()
   * @generated
   */
  void setCapGs(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Cap Gd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cap Gd</em>' attribute.
   * @see #setCapGd(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel_CapGd()
   * @model
   * @generated
   */
  BigDecimal getCapGd();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getCapGd <em>Cap Gd</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cap Gd</em>' attribute.
   * @see #getCapGd()
   * @generated
   */
  void setCapGd(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Gate Potential</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gate Potential</em>' attribute.
   * @see #setGatePotential(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel_GatePotential()
   * @model
   * @generated
   */
  BigDecimal getGatePotential();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getGatePotential <em>Gate Potential</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gate Potential</em>' attribute.
   * @see #getGatePotential()
   * @generated
   */
  void setGatePotential(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Gate Saturation Current</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gate Saturation Current</em>' attribute.
   * @see #setGateSaturationCurrent(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel_GateSaturationCurrent()
   * @model
   * @generated
   */
  BigDecimal getGateSaturationCurrent();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getGateSaturationCurrent <em>Gate Saturation Current</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gate Saturation Current</em>' attribute.
   * @see #getGateSaturationCurrent()
   * @generated
   */
  void setGateSaturationCurrent(BigDecimal value);

  /**
   * Returns the value of the '<em><b>B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>B</em>' attribute.
   * @see #setB(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel_B()
   * @model
   * @generated
   */
  BigDecimal getB();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getB <em>B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>B</em>' attribute.
   * @see #getB()
   * @generated
   */
  void setB(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Flicker Noise Coefficient</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flicker Noise Coefficient</em>' attribute.
   * @see #setFlickerNoiseCoefficient(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel_FlickerNoiseCoefficient()
   * @model
   * @generated
   */
  BigDecimal getFlickerNoiseCoefficient();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getFlickerNoiseCoefficient <em>Flicker Noise Coefficient</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Flicker Noise Coefficient</em>' attribute.
   * @see #getFlickerNoiseCoefficient()
   * @generated
   */
  void setFlickerNoiseCoefficient(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Flicker Noise Exponent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flicker Noise Exponent</em>' attribute.
   * @see #setFlickerNoiseExponent(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel_FlickerNoiseExponent()
   * @model
   * @generated
   */
  BigDecimal getFlickerNoiseExponent();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getFlickerNoiseExponent <em>Flicker Noise Exponent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Flicker Noise Exponent</em>' attribute.
   * @see #getFlickerNoiseExponent()
   * @generated
   */
  void setFlickerNoiseExponent(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Depletion Cap Coefficient</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Depletion Cap Coefficient</em>' attribute.
   * @see #setDepletionCapCoefficient(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel_DepletionCapCoefficient()
   * @model
   * @generated
   */
  BigDecimal getDepletionCapCoefficient();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getDepletionCapCoefficient <em>Depletion Cap Coefficient</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Depletion Cap Coefficient</em>' attribute.
   * @see #getDepletionCapCoefficient()
   * @generated
   */
  void setDepletionCapCoefficient(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Nominal Temperature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nominal Temperature</em>' attribute.
   * @see #setNominalTemperature(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getJFETModel_NominalTemperature()
   * @model
   * @generated
   */
  BigDecimal getNominalTemperature();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.JFETModel#getNominalTemperature <em>Nominal Temperature</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nominal Temperature</em>' attribute.
   * @see #getNominalTemperature()
   * @generated
   */
  void setNominalTemperature(BigDecimal value);

} // JFETModel
