/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.xSpice;

import java.math.BigDecimal;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MOSFET Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getLevel <em>Level</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getVt0 <em>Vt0</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getTransconductance <em>Transconductance</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getGamma <em>Gamma</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getPhi <em>Phi</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getLambda <em>Lambda</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getDrainResistance <em>Drain Resistance</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getSourceResistance <em>Source Resistance</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getCapBd <em>Cap Bd</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getCapBs <em>Cap Bs</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getJunctionSatCur <em>Junction Sat Cur</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getBulkJunctionPotential <em>Bulk Junction Potential</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getGateSourceOverlapCapFactor <em>Gate Source Overlap Cap Factor</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getGateDrainOverlapCapFactor <em>Gate Drain Overlap Cap Factor</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getGateBulkOverlapCapFactor <em>Gate Bulk Overlap Cap Factor</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getSheetResistance <em>Sheet Resistance</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getBulkCapFactor <em>Bulk Cap Factor</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getBulkJunctionBotGradingCoefficient <em>Bulk Junction Bot Grading Coefficient</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getSidewallCapFactor <em>Sidewall Cap Factor</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getBulkJunctionSideGradingCoefficient <em>Bulk Junction Side Grading Coefficient</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getJunctionSatCurDensity <em>Junction Sat Cur Density</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getOxideThickness <em>Oxide Thickness</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getSubstrateDoping <em>Substrate Doping</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getSurfaceStateDensity <em>Surface State Density</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getNfs <em>Nfs</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getGateType <em>Gate Type</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getXj <em>Xj</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getLateralDiffusion <em>Lateral Diffusion</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getSurfaceMobility <em>Surface Mobility</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getFlickerNoiseCoefficient <em>Flicker Noise Coefficient</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getFlickerNoiseExponent <em>Flicker Noise Exponent</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getForwardCapDepletionCoefficient <em>Forward Cap Depletion Coefficient</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getNominalTemperature <em>Nominal Temperature</em>}</li>
 * </ul>
 *
 * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel()
 * @model
 * @generated
 */
public interface MOSFETModel extends Entity
{
  /**
   * Returns the value of the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level</em>' attribute.
   * @see #setLevel(int)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_Level()
   * @model
   * @generated
   */
  int getLevel();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getLevel <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level</em>' attribute.
   * @see #getLevel()
   * @generated
   */
  void setLevel(int value);

  /**
   * Returns the value of the '<em><b>Vt0</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vt0</em>' attribute.
   * @see #setVt0(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_Vt0()
   * @model
   * @generated
   */
  BigDecimal getVt0();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getVt0 <em>Vt0</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vt0</em>' attribute.
   * @see #getVt0()
   * @generated
   */
  void setVt0(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Transconductance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transconductance</em>' attribute.
   * @see #setTransconductance(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_Transconductance()
   * @model
   * @generated
   */
  BigDecimal getTransconductance();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getTransconductance <em>Transconductance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transconductance</em>' attribute.
   * @see #getTransconductance()
   * @generated
   */
  void setTransconductance(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Gamma</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gamma</em>' attribute.
   * @see #setGamma(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_Gamma()
   * @model
   * @generated
   */
  BigDecimal getGamma();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getGamma <em>Gamma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gamma</em>' attribute.
   * @see #getGamma()
   * @generated
   */
  void setGamma(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Phi</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Phi</em>' attribute.
   * @see #setPhi(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_Phi()
   * @model
   * @generated
   */
  BigDecimal getPhi();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getPhi <em>Phi</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Phi</em>' attribute.
   * @see #getPhi()
   * @generated
   */
  void setPhi(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Lambda</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lambda</em>' attribute.
   * @see #setLambda(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_Lambda()
   * @model
   * @generated
   */
  BigDecimal getLambda();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getLambda <em>Lambda</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lambda</em>' attribute.
   * @see #getLambda()
   * @generated
   */
  void setLambda(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Drain Resistance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Drain Resistance</em>' attribute.
   * @see #setDrainResistance(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_DrainResistance()
   * @model
   * @generated
   */
  BigDecimal getDrainResistance();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getDrainResistance <em>Drain Resistance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Drain Resistance</em>' attribute.
   * @see #getDrainResistance()
   * @generated
   */
  void setDrainResistance(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Source Resistance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Resistance</em>' attribute.
   * @see #setSourceResistance(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_SourceResistance()
   * @model
   * @generated
   */
  BigDecimal getSourceResistance();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getSourceResistance <em>Source Resistance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Resistance</em>' attribute.
   * @see #getSourceResistance()
   * @generated
   */
  void setSourceResistance(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Cap Bd</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cap Bd</em>' attribute.
   * @see #setCapBd(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_CapBd()
   * @model
   * @generated
   */
  BigDecimal getCapBd();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getCapBd <em>Cap Bd</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cap Bd</em>' attribute.
   * @see #getCapBd()
   * @generated
   */
  void setCapBd(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Cap Bs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cap Bs</em>' attribute.
   * @see #setCapBs(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_CapBs()
   * @model
   * @generated
   */
  BigDecimal getCapBs();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getCapBs <em>Cap Bs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cap Bs</em>' attribute.
   * @see #getCapBs()
   * @generated
   */
  void setCapBs(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Junction Sat Cur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Junction Sat Cur</em>' attribute.
   * @see #setJunctionSatCur(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_JunctionSatCur()
   * @model
   * @generated
   */
  BigDecimal getJunctionSatCur();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getJunctionSatCur <em>Junction Sat Cur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Junction Sat Cur</em>' attribute.
   * @see #getJunctionSatCur()
   * @generated
   */
  void setJunctionSatCur(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Bulk Junction Potential</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bulk Junction Potential</em>' attribute.
   * @see #setBulkJunctionPotential(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_BulkJunctionPotential()
   * @model
   * @generated
   */
  BigDecimal getBulkJunctionPotential();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getBulkJunctionPotential <em>Bulk Junction Potential</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bulk Junction Potential</em>' attribute.
   * @see #getBulkJunctionPotential()
   * @generated
   */
  void setBulkJunctionPotential(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Gate Source Overlap Cap Factor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gate Source Overlap Cap Factor</em>' attribute.
   * @see #setGateSourceOverlapCapFactor(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_GateSourceOverlapCapFactor()
   * @model
   * @generated
   */
  BigDecimal getGateSourceOverlapCapFactor();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getGateSourceOverlapCapFactor <em>Gate Source Overlap Cap Factor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gate Source Overlap Cap Factor</em>' attribute.
   * @see #getGateSourceOverlapCapFactor()
   * @generated
   */
  void setGateSourceOverlapCapFactor(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Gate Drain Overlap Cap Factor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gate Drain Overlap Cap Factor</em>' attribute.
   * @see #setGateDrainOverlapCapFactor(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_GateDrainOverlapCapFactor()
   * @model
   * @generated
   */
  BigDecimal getGateDrainOverlapCapFactor();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getGateDrainOverlapCapFactor <em>Gate Drain Overlap Cap Factor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gate Drain Overlap Cap Factor</em>' attribute.
   * @see #getGateDrainOverlapCapFactor()
   * @generated
   */
  void setGateDrainOverlapCapFactor(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Gate Bulk Overlap Cap Factor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gate Bulk Overlap Cap Factor</em>' attribute.
   * @see #setGateBulkOverlapCapFactor(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_GateBulkOverlapCapFactor()
   * @model
   * @generated
   */
  BigDecimal getGateBulkOverlapCapFactor();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getGateBulkOverlapCapFactor <em>Gate Bulk Overlap Cap Factor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gate Bulk Overlap Cap Factor</em>' attribute.
   * @see #getGateBulkOverlapCapFactor()
   * @generated
   */
  void setGateBulkOverlapCapFactor(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Sheet Resistance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sheet Resistance</em>' attribute.
   * @see #setSheetResistance(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_SheetResistance()
   * @model
   * @generated
   */
  BigDecimal getSheetResistance();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getSheetResistance <em>Sheet Resistance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sheet Resistance</em>' attribute.
   * @see #getSheetResistance()
   * @generated
   */
  void setSheetResistance(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Bulk Cap Factor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bulk Cap Factor</em>' attribute.
   * @see #setBulkCapFactor(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_BulkCapFactor()
   * @model
   * @generated
   */
  BigDecimal getBulkCapFactor();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getBulkCapFactor <em>Bulk Cap Factor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bulk Cap Factor</em>' attribute.
   * @see #getBulkCapFactor()
   * @generated
   */
  void setBulkCapFactor(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Bulk Junction Bot Grading Coefficient</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bulk Junction Bot Grading Coefficient</em>' attribute.
   * @see #setBulkJunctionBotGradingCoefficient(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_BulkJunctionBotGradingCoefficient()
   * @model
   * @generated
   */
  BigDecimal getBulkJunctionBotGradingCoefficient();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getBulkJunctionBotGradingCoefficient <em>Bulk Junction Bot Grading Coefficient</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bulk Junction Bot Grading Coefficient</em>' attribute.
   * @see #getBulkJunctionBotGradingCoefficient()
   * @generated
   */
  void setBulkJunctionBotGradingCoefficient(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Sidewall Cap Factor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sidewall Cap Factor</em>' attribute.
   * @see #setSidewallCapFactor(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_SidewallCapFactor()
   * @model
   * @generated
   */
  BigDecimal getSidewallCapFactor();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getSidewallCapFactor <em>Sidewall Cap Factor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sidewall Cap Factor</em>' attribute.
   * @see #getSidewallCapFactor()
   * @generated
   */
  void setSidewallCapFactor(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Bulk Junction Side Grading Coefficient</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bulk Junction Side Grading Coefficient</em>' attribute.
   * @see #setBulkJunctionSideGradingCoefficient(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_BulkJunctionSideGradingCoefficient()
   * @model
   * @generated
   */
  BigDecimal getBulkJunctionSideGradingCoefficient();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getBulkJunctionSideGradingCoefficient <em>Bulk Junction Side Grading Coefficient</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bulk Junction Side Grading Coefficient</em>' attribute.
   * @see #getBulkJunctionSideGradingCoefficient()
   * @generated
   */
  void setBulkJunctionSideGradingCoefficient(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Junction Sat Cur Density</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Junction Sat Cur Density</em>' attribute.
   * @see #setJunctionSatCurDensity(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_JunctionSatCurDensity()
   * @model
   * @generated
   */
  BigDecimal getJunctionSatCurDensity();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getJunctionSatCurDensity <em>Junction Sat Cur Density</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Junction Sat Cur Density</em>' attribute.
   * @see #getJunctionSatCurDensity()
   * @generated
   */
  void setJunctionSatCurDensity(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Oxide Thickness</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Oxide Thickness</em>' attribute.
   * @see #setOxideThickness(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_OxideThickness()
   * @model
   * @generated
   */
  BigDecimal getOxideThickness();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getOxideThickness <em>Oxide Thickness</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Oxide Thickness</em>' attribute.
   * @see #getOxideThickness()
   * @generated
   */
  void setOxideThickness(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Substrate Doping</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Substrate Doping</em>' attribute.
   * @see #setSubstrateDoping(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_SubstrateDoping()
   * @model
   * @generated
   */
  BigDecimal getSubstrateDoping();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getSubstrateDoping <em>Substrate Doping</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Substrate Doping</em>' attribute.
   * @see #getSubstrateDoping()
   * @generated
   */
  void setSubstrateDoping(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Surface State Density</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Surface State Density</em>' attribute.
   * @see #setSurfaceStateDensity(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_SurfaceStateDensity()
   * @model
   * @generated
   */
  BigDecimal getSurfaceStateDensity();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getSurfaceStateDensity <em>Surface State Density</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Surface State Density</em>' attribute.
   * @see #getSurfaceStateDensity()
   * @generated
   */
  void setSurfaceStateDensity(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Nfs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nfs</em>' attribute.
   * @see #setNfs(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_Nfs()
   * @model
   * @generated
   */
  BigDecimal getNfs();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getNfs <em>Nfs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nfs</em>' attribute.
   * @see #getNfs()
   * @generated
   */
  void setNfs(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Gate Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gate Type</em>' attribute.
   * @see #setGateType(String)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_GateType()
   * @model
   * @generated
   */
  String getGateType();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getGateType <em>Gate Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gate Type</em>' attribute.
   * @see #getGateType()
   * @generated
   */
  void setGateType(String value);

  /**
   * Returns the value of the '<em><b>Xj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xj</em>' attribute.
   * @see #setXj(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_Xj()
   * @model
   * @generated
   */
  BigDecimal getXj();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getXj <em>Xj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xj</em>' attribute.
   * @see #getXj()
   * @generated
   */
  void setXj(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Lateral Diffusion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lateral Diffusion</em>' attribute.
   * @see #setLateralDiffusion(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_LateralDiffusion()
   * @model
   * @generated
   */
  BigDecimal getLateralDiffusion();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getLateralDiffusion <em>Lateral Diffusion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lateral Diffusion</em>' attribute.
   * @see #getLateralDiffusion()
   * @generated
   */
  void setLateralDiffusion(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Surface Mobility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Surface Mobility</em>' attribute.
   * @see #setSurfaceMobility(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_SurfaceMobility()
   * @model
   * @generated
   */
  BigDecimal getSurfaceMobility();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getSurfaceMobility <em>Surface Mobility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Surface Mobility</em>' attribute.
   * @see #getSurfaceMobility()
   * @generated
   */
  void setSurfaceMobility(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Flicker Noise Coefficient</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flicker Noise Coefficient</em>' attribute.
   * @see #setFlickerNoiseCoefficient(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_FlickerNoiseCoefficient()
   * @model
   * @generated
   */
  BigDecimal getFlickerNoiseCoefficient();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getFlickerNoiseCoefficient <em>Flicker Noise Coefficient</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Flicker Noise Coefficient</em>' attribute.
   * @see #getFlickerNoiseCoefficient()
   * @generated
   */
  void setFlickerNoiseCoefficient(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Flicker Noise Exponent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flicker Noise Exponent</em>' attribute.
   * @see #setFlickerNoiseExponent(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_FlickerNoiseExponent()
   * @model
   * @generated
   */
  BigDecimal getFlickerNoiseExponent();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getFlickerNoiseExponent <em>Flicker Noise Exponent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Flicker Noise Exponent</em>' attribute.
   * @see #getFlickerNoiseExponent()
   * @generated
   */
  void setFlickerNoiseExponent(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Forward Cap Depletion Coefficient</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forward Cap Depletion Coefficient</em>' attribute.
   * @see #setForwardCapDepletionCoefficient(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_ForwardCapDepletionCoefficient()
   * @model
   * @generated
   */
  BigDecimal getForwardCapDepletionCoefficient();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getForwardCapDepletionCoefficient <em>Forward Cap Depletion Coefficient</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Forward Cap Depletion Coefficient</em>' attribute.
   * @see #getForwardCapDepletionCoefficient()
   * @generated
   */
  void setForwardCapDepletionCoefficient(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Nominal Temperature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nominal Temperature</em>' attribute.
   * @see #setNominalTemperature(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getMOSFETModel_NominalTemperature()
   * @model
   * @generated
   */
  BigDecimal getNominalTemperature();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.MOSFETModel#getNominalTemperature <em>Nominal Temperature</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nominal Temperature</em>' attribute.
   * @see #getNominalTemperature()
   * @generated
   */
  void setNominalTemperature(BigDecimal value);

} // MOSFETModel
