/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.xSpice;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sub Circuit Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.SubCircuitDefinition#getName <em>Name</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.SubCircuitDefinition#getPins <em>Pins</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.SubCircuitDefinition#getDefinitions <em>Definitions</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.SubCircuitDefinition#getEntities <em>Entities</em>}</li>
 * </ul>
 *
 * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getSubCircuitDefinition()
 * @model
 * @generated
 */
public interface SubCircuitDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getSubCircuitDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.SubCircuitDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Pins</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pins</em>' attribute list.
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getSubCircuitDefinition_Pins()
   * @model unique="false"
   * @generated
   */
  EList<String> getPins();

  /**
   * Returns the value of the '<em><b>Definitions</b></em>' containment reference list.
   * The list contents are of type {@link com.xtext.ravornyo.xspice.xSpice.SubCircuitDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Definitions</em>' containment reference list.
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getSubCircuitDefinition_Definitions()
   * @model containment="true"
   * @generated
   */
  EList<SubCircuitDefinition> getDefinitions();

  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link com.xtext.ravornyo.xspice.xSpice.Entity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getSubCircuitDefinition_Entities()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntities();

} // SubCircuitDefinition
