/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.xSpice;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Voltage Export</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getVoltageExport()
 * @model
 * @generated
 */
public interface VoltageExport extends Export
{
} // VoltageExport
