/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.xSpice;

import java.math.BigDecimal;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Voltage Switch Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.VoltageSwitchModel#getThreshold <em>Threshold</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.VoltageSwitchModel#getHysteresis <em>Hysteresis</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.VoltageSwitchModel#getOnResistance <em>On Resistance</em>}</li>
 *   <li>{@link com.xtext.ravornyo.xspice.xSpice.VoltageSwitchModel#getOffResistance <em>Off Resistance</em>}</li>
 * </ul>
 *
 * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getVoltageSwitchModel()
 * @model
 * @generated
 */
public interface VoltageSwitchModel extends Entity
{
  /**
   * Returns the value of the '<em><b>Threshold</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Threshold</em>' attribute.
   * @see #setThreshold(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getVoltageSwitchModel_Threshold()
   * @model
   * @generated
   */
  BigDecimal getThreshold();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.VoltageSwitchModel#getThreshold <em>Threshold</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Threshold</em>' attribute.
   * @see #getThreshold()
   * @generated
   */
  void setThreshold(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Hysteresis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hysteresis</em>' attribute.
   * @see #setHysteresis(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getVoltageSwitchModel_Hysteresis()
   * @model
   * @generated
   */
  BigDecimal getHysteresis();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.VoltageSwitchModel#getHysteresis <em>Hysteresis</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hysteresis</em>' attribute.
   * @see #getHysteresis()
   * @generated
   */
  void setHysteresis(BigDecimal value);

  /**
   * Returns the value of the '<em><b>On Resistance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>On Resistance</em>' attribute.
   * @see #setOnResistance(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getVoltageSwitchModel_OnResistance()
   * @model
   * @generated
   */
  BigDecimal getOnResistance();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.VoltageSwitchModel#getOnResistance <em>On Resistance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>On Resistance</em>' attribute.
   * @see #getOnResistance()
   * @generated
   */
  void setOnResistance(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Off Resistance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Off Resistance</em>' attribute.
   * @see #setOffResistance(BigDecimal)
   * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage#getVoltageSwitchModel_OffResistance()
   * @model
   * @generated
   */
  BigDecimal getOffResistance();

  /**
   * Sets the value of the '{@link com.xtext.ravornyo.xspice.xSpice.VoltageSwitchModel#getOffResistance <em>Off Resistance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Off Resistance</em>' attribute.
   * @see #getOffResistance()
   * @generated
   */
  void setOffResistance(BigDecimal value);

} // VoltageSwitchModel
