/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.xSpice;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.xtext.ravornyo.xspice.xSpice.XSpicePackage
 * @generated
 */
public interface XSpiceFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XSpiceFactory eINSTANCE = com.xtext.ravornyo.xspice.xSpice.impl.XSpiceFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Compilation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Compilation</em>'.
   * @generated
   */
  Compilation createCompilation();

  /**
   * Returns a new object of class '<em>Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity</em>'.
   * @generated
   */
  Entity createEntity();

  /**
   * Returns a new object of class '<em>Component</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component</em>'.
   * @generated
   */
  Component createComponent();

  /**
   * Returns a new object of class '<em>Sub Circuit Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sub Circuit Definition</em>'.
   * @generated
   */
  SubCircuitDefinition createSubCircuitDefinition();

  /**
   * Returns a new object of class '<em>Sub Circuit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sub Circuit</em>'.
   * @generated
   */
  SubCircuit createSubCircuit();

  /**
   * Returns a new object of class '<em>Resistor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Resistor</em>'.
   * @generated
   */
  Resistor createResistor();

  /**
   * Returns a new object of class '<em>Resistor Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Resistor Model</em>'.
   * @generated
   */
  ResistorModel createResistorModel();

  /**
   * Returns a new object of class '<em>Capacitor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Capacitor</em>'.
   * @generated
   */
  Capacitor createCapacitor();

  /**
   * Returns a new object of class '<em>Capacitor Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Capacitor Model</em>'.
   * @generated
   */
  CapacitorModel createCapacitorModel();

  /**
   * Returns a new object of class '<em>Inductor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inductor</em>'.
   * @generated
   */
  Inductor createInductor();

  /**
   * Returns a new object of class '<em>Mutual Inductance</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mutual Inductance</em>'.
   * @generated
   */
  MutualInductance createMutualInductance();

  /**
   * Returns a new object of class '<em>Voltage Switch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Voltage Switch</em>'.
   * @generated
   */
  VoltageSwitch createVoltageSwitch();

  /**
   * Returns a new object of class '<em>Voltage Switch Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Voltage Switch Model</em>'.
   * @generated
   */
  VoltageSwitchModel createVoltageSwitchModel();

  /**
   * Returns a new object of class '<em>Current Switch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Current Switch</em>'.
   * @generated
   */
  CurrentSwitch createCurrentSwitch();

  /**
   * Returns a new object of class '<em>Current Switch Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Current Switch Model</em>'.
   * @generated
   */
  CurrentSwitchModel createCurrentSwitchModel();

  /**
   * Returns a new object of class '<em>Diode</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Diode</em>'.
   * @generated
   */
  Diode createDiode();

  /**
   * Returns a new object of class '<em>Diode Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Diode Model</em>'.
   * @generated
   */
  DiodeModel createDiodeModel();

  /**
   * Returns a new object of class '<em>MOSFET</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MOSFET</em>'.
   * @generated
   */
  MOSFET createMOSFET();

  /**
   * Returns a new object of class '<em>MOSFET Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MOSFET Model</em>'.
   * @generated
   */
  MOSFETModel createMOSFETModel();

  /**
   * Returns a new object of class '<em>BJT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BJT</em>'.
   * @generated
   */
  BJT createBJT();

  /**
   * Returns a new object of class '<em>BJT Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BJT Model</em>'.
   * @generated
   */
  BJTModel createBJTModel();

  /**
   * Returns a new object of class '<em>JFET</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>JFET</em>'.
   * @generated
   */
  JFET createJFET();

  /**
   * Returns a new object of class '<em>JFET Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>JFET Model</em>'.
   * @generated
   */
  JFETModel createJFETModel();

  /**
   * Returns a new object of class '<em>VSource</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VSource</em>'.
   * @generated
   */
  VSource createVSource();

  /**
   * Returns a new object of class '<em>Current Source</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Current Source</em>'.
   * @generated
   */
  CurrentSource createCurrentSource();

  /**
   * Returns a new object of class '<em>VCVS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VCVS</em>'.
   * @generated
   */
  VCVS createVCVS();

  /**
   * Returns a new object of class '<em>VCCS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VCCS</em>'.
   * @generated
   */
  VCCS createVCCS();

  /**
   * Returns a new object of class '<em>CCCS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CCCS</em>'.
   * @generated
   */
  CCCS createCCCS();

  /**
   * Returns a new object of class '<em>CCVS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CCVS</em>'.
   * @generated
   */
  CCVS createCCVS();

  /**
   * Returns a new object of class '<em>Geometeric Sweep</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Geometeric Sweep</em>'.
   * @generated
   */
  GeometericSweep createGeometericSweep();

  /**
   * Returns a new object of class '<em>Linear Sweep</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Linear Sweep</em>'.
   * @generated
   */
  LinearSweep createLinearSweep();

  /**
   * Returns a new object of class '<em>Octave Sweep</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Octave Sweep</em>'.
   * @generated
   */
  OctaveSweep createOctaveSweep();

  /**
   * Returns a new object of class '<em>Decade Sweep</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Decade Sweep</em>'.
   * @generated
   */
  DecadeSweep createDecadeSweep();

  /**
   * Returns a new object of class '<em>Parameter Sweep</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parameter Sweep</em>'.
   * @generated
   */
  ParameterSweep createParameterSweep();

  /**
   * Returns a new object of class '<em>Simulation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simulation</em>'.
   * @generated
   */
  Simulation createSimulation();

  /**
   * Returns a new object of class '<em>AC Simulation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AC Simulation</em>'.
   * @generated
   */
  ACSimulation createACSimulation();

  /**
   * Returns a new object of class '<em>DC Simulation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DC Simulation</em>'.
   * @generated
   */
  DCSimulation createDCSimulation();

  /**
   * Returns a new object of class '<em>Noise Simulation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Noise Simulation</em>'.
   * @generated
   */
  NoiseSimulation createNoiseSimulation();

  /**
   * Returns a new object of class '<em>Transient Simulation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transient Simulation</em>'.
   * @generated
   */
  TransientSimulation createTransientSimulation();

  /**
   * Returns a new object of class '<em>Output</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Output</em>'.
   * @generated
   */
  Output createOutput();

  /**
   * Returns a new object of class '<em>Print</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Print</em>'.
   * @generated
   */
  Print createPrint();

  /**
   * Returns a new object of class '<em>Plot</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Plot</em>'.
   * @generated
   */
  Plot createPlot();

  /**
   * Returns a new object of class '<em>Export</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Export</em>'.
   * @generated
   */
  Export createExport();

  /**
   * Returns a new object of class '<em>Voltage Export</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Voltage Export</em>'.
   * @generated
   */
  VoltageExport createVoltageExport();

  /**
   * Returns a new object of class '<em>Current Export</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Current Export</em>'.
   * @generated
   */
  CurrentExport createCurrentExport();

  /**
   * Returns a new object of class '<em>Waveform</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Waveform</em>'.
   * @generated
   */
  Waveform createWaveform();

  /**
   * Returns a new object of class '<em>Exp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exp</em>'.
   * @generated
   */
  Exp createExp();

  /**
   * Returns a new object of class '<em>Sine</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sine</em>'.
   * @generated
   */
  Sine createSine();

  /**
   * Returns a new object of class '<em>Pulse</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pulse</em>'.
   * @generated
   */
  Pulse createPulse();

  /**
   * Returns a new object of class '<em>PWL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PWL</em>'.
   * @generated
   */
  PWL createPWL();

  /**
   * Returns a new object of class '<em>SFFM</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SFFM</em>'.
   * @generated
   */
  SFFM createSFFM();

  /**
   * Returns a new object of class '<em>AM</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AM</em>'.
   * @generated
   */
  AM createAM();

  /**
   * Returns a new object of class '<em>Options</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Options</em>'.
   * @generated
   */
  Options createOptions();

  /**
   * Returns a new object of class '<em>Node Set</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Node Set</em>'.
   * @generated
   */
  NodeSet createNodeSet();

  /**
   * Returns a new object of class '<em>Initial Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial Condition</em>'.
   * @generated
   */
  InitialCondition createInitialCondition();

  /**
   * Returns a new object of class '<em>Node Set Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Node Set Entry</em>'.
   * @generated
   */
  NodeSetEntry createNodeSetEntry();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  XSpicePackage getXSpicePackage();

} //XSpiceFactory
