/**
 * generated by Xtext 2.18.0.M3
 */
package com.xtext.ravornyo.xspice.web;

import com.xtext.ravornyo.xspice.web.AbstractXSpiceWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class XSpiceWebModule extends AbstractXSpiceWebModule {
}
